// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-hputg5ERQW2iu1vKEQK-KzEzoPZTp8',
    appId: '1:880213859200:web:2bedfa5cf66eb4701b3f65',
    messagingSenderId: '880213859200',
    projectId: 'chat-2a218',
    authDomain: 'chat-2a218.firebaseapp.com',
    storageBucket: 'chat-2a218.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-03qSDFLtGZVO2lG8VlwgxMPugll2u8',
    appId: '1:880213859200:android:239672090aa0aed91b3f65',
    messagingSenderId: '880213859200',
    projectId: 'chat-2a218',
    storageBucket: 'chat-2a218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWx9XCX8exHuj-4Uhkt_mtK8MA6OgfHNE',
    appId: '1:880213859200:ios:baea6f32c3588f611b3f65',
    messagingSenderId: '880213859200',
    projectId: 'chat-2a218',
    storageBucket: 'chat-2a218.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWx9XCX8exHuj-4Uhkt_mtK8MA6OgfHNE',
    appId: '1:880213859200:ios:baea6f32c3588f611b3f65',
    messagingSenderId: '880213859200',
    projectId: 'chat-2a218',
    storageBucket: 'chat-2a218.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-hputg5ERQW2iu1vKEQK-KzEzoPZTp8',
    appId: '1:880213859200:web:d506e026d61c9baf1b3f65',
    messagingSenderId: '880213859200',
    projectId: 'chat-2a218',
    authDomain: 'chat-2a218.firebaseapp.com',
    storageBucket: 'chat-2a218.appspot.com',
  );
}
